<MyRoot>:
    orientation: "vertical"

    Label:
        text: "Hangman"
        font_name: "fonts/Plaguard.otf"
        font_size: 84
        color: 0, 1, 0, 1
        color: 0, 1, 0, 1

    Image:
        source: root.HANGMAN_IMG
        size_hint: 1, 2


    Label:
        text: "Available Letters"
        size_hint: 1, 0.75
        font_name: "fonts/Plaguard.otf"
        font_size: 32
        color: 0, 1, 0, 1
    
    ButtonsLayout:
